### PR TITLE
[COST-4407] Add service account support

### PR DESCRIPTION
**Pull request by chambridge**
* Add service account support as basic auth is becoming EOL

### Test
In order to test checkout the branch.
- Build the package `make install`
- Create a service account
- Add environment variables `HCC_SERVICE_ACCOUNT_ID`, `HCC_SERVICE_ACCOUNT_SECRET`, and `HCC_TOKEN_URL` (depending on your environment
- Set your environment
- Run a command to send OCP data to the service: `nise report ocp --insights-upload https://console.redhat.com/api/ingress/v1/upload -s 2023-11-01 --ocp-cluster-id my-test-upload`
- Check listener logs:
```
[2023-11-03 15:50:09,594] INFO None 1 {'message': "Extracting Payload for msg: {'account': '', 'category': 'tar', 'content_type': 'application/vnd.redhat.hccm.tar+tgz', 'metadata': {'reporter': '', 'stale_timestamp': '0001-01-01T00:00:00Z'}, 'request_id': '09740dcb4f05418c84dd0cc6ccabebc6', 'principal': 'wwwww', 'org_id': 'yyyyyy', 'service': 'hccm', 'size': 974, 'url': 'https'
[2023-11-03 15:50:09,685] INFO None 1 {'message': 'Payload with the request id 09740dcb4f05418c84dd0cc6ccabebc6 from cluster my-test-upload is part of the report with manifest id 4e0e0dde-228e-4166-960f-de536237883e', 'tracing_id': '09740dcb4f05418c84dd0cc6ccabebc6', 'account': '', 'org_id': 'yyyyyyy', 'request_id': '09740dcb4f05418c84dd0cc6ccabebc6', 'cluster_id': 'my-test-upload', 'manifest_uuid': '4e0e0dde-228e-4166-960f-de536237883e'}
[2023-11-03 15:50:09,703] WARNING None 1 {'message': 'Recieved unexpected OCP report from my-test-upload', 'tracing_id': '4e0e0dde-228e-4166-960f-de536237883e', 'account': '', 'org_id': 'yyyyyy', 'request_id': '09740dcb4f05418c84dd0cc6ccabebc6', 'cluster_id': 'my-test-upload', 'manifest_uuid': '4e0e0dde-228e-4166-960f-de536237883e'}
```

### CODE REVIEW

**Comment by djnakabaale** [comment]
testing instructions look good to me, seeing logs in listener:

<details>

```log
[2023-11-06 14:39:08,250] INFO None 1 {'message': "Extracting Payload for msg: {'account': '', 'category': 'tar', 'content_type': 'application/vnd.redhat.hccm.tar+tgz', 'metadata': {'reporter': '', 'stale_timestamp': '0001-01-01T00:00:00Z'}, 'request_id': '7af4b9d15a26426aa46059a7a5e8e70d', 'principal': '11009103', 'org_id': '11009103', 'service': 'hccm', 'size': 171702, 'url': 'https...'}}
[2023-11-06 14:39:08,355] INFO None 1 {'message': 'Payload with the request id 7af4b9d15a26426aa46059a7a5e8e70d from cluster my-test-upload is part of the report with manifest id efbef9fe-e5d0-491d-a05c-f3796bb3524e', 'tracing_id': '7af4b9d15a26426aa46059a7a5e8e70d', 'account': '', 'org_id': '11009103', 'request_id': '7af4b9d15a26426aa46059a7a5e8e70d', 'cluster_id': 'my-test-upload', 'manifest_uuid': 'efbef9fe-e5d0-491d-a05c-f3796bb3524e'}
[2023-11-06 14:39:08,376] WARNING None 1 {'message': 'Recieved unexpected OCP report from my-test-upload', 'tracing_id': 'efbef9fe-e5d0-491d-a05c-f3796bb3524e', 'account': '', 'org_id': '11009103', 'request_id': '7af4b9d15a26426aa46059a7a5e8e70d', 'cluster_id': 'my-test-upload', 'manifest_uuid': 'efbef9fe-e5d0-491d-a05c-f3796bb3524e'}
```
</details>

**Review by djnakabaale — COMMENTED** [review]
Looks good to me, one nitpick is to update the version number

**Comment by chambridge** [comment]
> Looks good to me, one nitpick is to update the version number

I've updated the version.

**Review by djnakabaale — APPROVED** [review]
lgtm 👍🏾

**Pull request merged**
